spring:
  application:
    name: plantory-project-BE
  #  security:
  #    user:
  #      name: admin
  #      password: 1234
  cloud:
    gcp:
      storage:
        project-id: logical-voyage-477015-j4

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/plantorydb
    username: pldbid
    password: pldbpw

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml

#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    open-in-view: false
#    generate-ddl: true


server:
  servlet:
    session:
      cookie:
        same-site: Lax
  port: 9000

openapi:
  nongsaro:
    key: ${OPENAPI_NONGSARO_KEY}

security:
  remember-me:
    key: dev-test-key   # ???


#security:
#  remember-me:
#    key: ${REMEMBER_ME_KEY} #AWS ??? ??? export REMEMBER_ME_KEY="?????"??

jwt:
  issuer: kimjaewook8581@gmail.com
  secret: study-springboot-jwt-secret-key-256bit!!
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000
